<template>
    <div class="container">
        <div class="row">
            <div class="col-md-10" style="margin-left:3%; margin-top:2%;">
                <router-link to="/transaction" class="btn btn-info btn-lg black"><i class="fa fa-arrow-left black"></i>Back To Invoice</router-link>
            </div>
            <div style="margin-left:1%; margin-top:2%;">
                <button id="printInvoice" class="btn btn-info btn-lg" @click="printInvoice"><i class="fa fa-print"></i> Print</button>
            </div>
        </div>
        <div id="invoice">
            <div class="invoice overflow-auto">
                <div style="min-width: 600px">
                    <header>
                        <div class="row">
                            <div class="col">
                                <a target="_blank" href="https://lobianijs.com">
                                <!-- <h1>Garment Shop</h1> -->
                                <img src="logo.png" data-holder-rendered="true" width="179" height="110"/>
                                </a>
                            </div>
                            <div class="col company-details">
                                <br>
                                <h2 class="name">
                                    Generated by: {{userName}}
                                </h2>
                            </div>
                        </div>
                    </header>
                    <main>
                        <div class="row contacts">
                            <div class="col invoice-to">
                                <div class="text-gray-light">INVOICE TO:</div>
                                <h2 class="to">{{masterTransaction.client.name}}</h2>
                                <div class="address">{{masterTransaction.client.contact}}</div>
                            </div>
                            <div class="col invoice-details">
                                <h1 class="invoice-id">INVOICE # {{masterTransaction.id}}</h1>
                                <div class="date">Date of Invoice: {{masterTransaction.created_at | myDate}}</div>
                            </div>
                        </div>
                        <table border="0" cellspacing="0" cellpadding="0">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th class="text-left">PRODUCT</th>
                                    <th class="text-right">COLOR</th>
                                    <th class="text-right">QUANTITY</th>
                                    <th class="text-right">BASE PRICE</th>
                                    <th class="text-right">DISCOUNT</th>
                                    <th class="text-right">TOTAL</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr v-for="(childTransaction,index) in childTransactions">
                                    <td class="no">{{index+1}}</td>
                                    <td class="text-left"><h3>{{childTransaction.product.name}}</h3></td>
                                    <td class="qty">{{childTransaction.color.name}}</td>
                                    <td class="qty">{{childTransaction.quantity}}</td>
                                    <td class="unit">{{childTransaction.price}}</td>
                                    <td class="unit">{{childTransaction.discount}}</td>
                                    <td class="total">{{childTransaction.total}}</td>
                                </tr>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="3"></td>
                                    <td colspan="3">SUBTOTAL</td>
                                    <td>{{masterTransaction.price}}</td>
                                </tr>
                                <tr>
                                    <td colspan="3"></td>
                                    <td colspan="3">Discount</td>
                                    <td>{{masterTransaction.discount}}</td>
                                </tr>
                                <tr>
                                    <td colspan="3"></td>
                                    <td colspan="3">GRAND TOTAL</td>
                                    <td>{{masterTransaction.total}}</td>
                                </tr>
                            </tfoot>
                        </table>
                        <div class="thanks">Thank you!</div>
                    </main>
                    <footer>
                        Copyright C2P. All rights reserved.
                    </footer>
                </div>
                <!--DO NOT DELETE THIS div. IT is responsible for showing footer always at the bottom-->
                <div></div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        data()
        {
            return{
                userName:'',
                masterTransaction: {},
                childTransactions: {},
            }
        },
        methods:
        {
            loadUserName(){
                axios.get('garment/api/get_user_name')
                .then(response => {
                    this.userName = response.data.name;
                });
            },
            loadMasterTransaction(id)
            {
                axios.get('garment/api/master_transaction/'+id)
                .then(({data}) => 
                {
                    this.masterTransaction = data;
                });
                this.loadChildTransactions(id);
            },
            loadChildTransactions(id)
            {
                axios.get('garment/api/child_transaction/'+id)
                .then(({data}) => 
                {
                    this.childTransactions = data;
                });
            },
            printInvoice(){
                 Popup($('#invoice')[0].outerHTML);
                    function Popup(data) 
                    {
                        window.print();
                        return true;
                    }
            }
        },
        mounted() {
            this.loadUserName();
            this.loadMasterTransaction(this.$route.params.id);
        }
    };
</script>

